# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\testcasezlive\live.har





from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLive(HttpRunner):

    

    config = Config("testcase description").verify(False)

    teststeps = [
        
            Step(RunRequest("/livevideos/createLive").post("https://courseapi.ulearning.cn/livevideos/createLive").with_headers(**{'Host': 'courseapi.ulearning.cn', 'Connection': 'keep-alive', 'Content-Length': '1293', 'sec-ch-ua': '"Chromium";v="88", "Google Chrome";v="88", ";Not A Brand";v="99"', 'Accept': '*/*', 'Authorization': '91981C807EF1529062F579D87040FDE1', 'sec-ch-ua-mobile': '?0', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36', 'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryvp9YC2QU4dEkJef5', 'Origin': 'https://courseweb.ulearning.cn', 'Sec-Fetch-Site': 'same-site', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Dest': 'empty', 'Referer': 'https://courseweb.ulearning.cn/', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'zh-CN,zh;q=0.9'}).with_data("------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="id"

0
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="creator"

0
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="classID"

398269,388773,353946
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="ocId"

72903
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="liveClassName"

啊啊啊
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="anchorName"

陈庆港国内国外通测试账号
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="liveClassDesc"

啊啊啊
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="startTime"

1618456800000
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="duration"

12
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="openState"

0
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="roomType"

4
------WebKitFormBoundaryvp9YC2QU4dEkJef5
Content-Disposition: form-data; name="liveClassType"

null
------WebKitFormBoundaryvp9YC2QU4dEkJef5--
").validate().assert_equal("status_code", 200).assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")),
        
    ]

if __name__ == "__main__":
    TestCaseLive().test_start()
